### PR TITLE
SOL-112930:

### PR DESCRIPTION
**Pull request by RagnarPaulson**
Create a snippet to demonstrate how to set websockets in the host property.

### CODE REVIEW

**Comment by aaron-613** [comment]
@RagnarPaulson Is this ready to be reviewed?  It's still in Draft.

**Comment by RagnarPaulson** [comment]
> @RagnarPaulson Is this ready to be reviewed? It's still in Draft.

Websockets has not been released yet.   You can review it, which is the goal with draft PRs, but you can't merge it until we release JCSMP 10.24.0

**Comment by aaron-613** [comment]
How can I review it if I can't run it..? 🤔

**Comment by aaron-613** [comment]
Snippet is good, have tested it actually works in JCSMP with another app.

**Review by aaron-613 — APPROVED** [review]
Yup, all good.

**Pull request merged**
