### PR TITLE
SOL-106405: Added HowTo snippet for enabling payload compression

### PR DESCRIPTION
**Pull request by aelsammak**
This snippet demonstrates how to enable payload compression on a session.

### CODE REVIEW

**Comment by Mrc0113** [comment]
Hi @aelsammak, 
Any reason this is still marked as draft?

**Comment by aelsammak** [comment]
> Hi @aelsammak, Any reason this is still marked as draft?

The process for developer snippets requires us to create a draft-PR with the new file that can be reviewed by DA.

Only once the feature is released, it can be converted to a regular PR. 😄

**Comment by Mrc0113** [comment]
> The process for developer snippets requires us to create a draft-PR with the new file that can be reviewed by DA.
> Only once the feature is released, it can be converted to a regular PR. 😄

Bad question on my end. Do you know when the feature is scheduled to be released? 
(And thank you for following the process!)

**Comment by aelsammak** [comment]
> > The process for developer snippets requires us to create a draft-PR with the new file that can be reviewed by DA.
> > Only once the feature is released, it can be converted to a regular PR. 😄
> 
> Bad question on my end. Do you know when the feature is scheduled to be released? (And thank you for following the process!)

No problem at all, a stale draft-PR would make me question it as well! 

The feature is scheduled to be released in April.

**Comment by aaron-613** [comment]
Is there a way to manually unzip the payload if not using a new Solace API?  Like MQTT or something else.  Is it just regular zip?

**Comment by aelsammak** [comment]
> Is there a way to manually unzip the payload if not using a new Solace API? Like MQTT or something else. Is it just regular zip?

Currently, receivers using the new Solace API will automatically decompress the Solace published payload and there is no way to disable that. An older Solace API receiver will receive the payload as bytes and can handle the decompression in their own application. Since we are utilizing the existing content-encoding property, consumers can check if the payload was compressed by determining if this property contains 'deflate'.

**Comment by aaron-613** [comment]
Has this feature been released yet?

**Comment by aelsammak** [comment]
> Has this feature been released yet?

Not yet, but it is scheduled to be released in JCSMP/JMS 10.24.0 which should be out by the end of the month!

**Comment by aelsammak** [comment]
@Mrc0113  JCSMP/JMS 10.24.0 was released. This PR is being converted from draft to ready-for-review!

**Review by aaron-613 — APPROVED** [review]
Yup, tested in some working code, looks good.  New APIs will automatically detect and decompress when encountering this.

**Pull request merged**
