### PR TITLE
fixed deprecation warnings on older samples

### PR DESCRIPTION
**Pull request by aaron-613**
Flagged by user "Robert" on Solace Community, needed to update a few of the older samples to remove deprecations warnings.

Done.

https://solace.community/discussion/1153/samples-for-jcsmp-use-deprecated-classes

### CODE REVIEW

**Comment by Mrc0113** [comment]
@aaron-613 thanks for adding the comments. Since you didn't just remove them I'm assuming you still see value in having them stay? Do you think it would make sense to move them into a deprecated package as well? It might make it slightly more obvious for folks navigating the samples.

**Comment by aaron-613** [comment]
@Mrc0113 They were left there as the current tutorials still point to them.  That's the only reason.  Sure, I can move them to a different folder?

**Comment by Mrc0113** [comment]
> @Mrc0113 They were left there as the current tutorials still point to them. That's the only reason. Sure, I can move them to a different folder?

Good point. Do you know if the code in the existing tutorials can be directly swapped out for the non-deprecated code in the newer samples that you referred to in the comments of each class? or would it require more in depth re-writing of the tutorials?

**Comment by aaron-613** [comment]
@Mrc0113 As tutorials are being updated as-we-speak, I'll leave the tutorials pointing to these apps for now as they should be live in the new couple weeks and will reference the new "patterns" ones.  Then we can permanently remove these older (poor) samples.

**Pull request merged**
